# Generated by Django 4.2 on 2025-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='province',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='creation_date',
            new_name='publication_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='country',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
    ]
